version: '3.3'
services:
    minio:
        ports:
            - '9000:9000'
            - '9090:9090'
        container_name: minio
        volumes:
            - '/Users/puzzzik/Developer/networking/data:/data'
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        image: quay.io/minio/minio 
        command: server /data --console-address ":9090"